name: CI Build and Test for PR

permissions:
  contents: read

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: check format
        run: make check_format

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: build and test
        run: make docker_tests

  precommits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: "3.9"

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: "1.21.5"

      - name: run pre-commits
        run: |
          make precommit_install
          pre-commit run -a

      # If previous stage fails, print resolution steps
      - if: ${{ failure() }}
        name: Read for resolution steps
        run: |
          echo "Pre-commits failed! Run 'make precommit_install' then 'pre-commits run -a' to fix."
          exit 1
